[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "12.16.2"
  NODE_ENV = "production"

[dev]
  command = "npm run watch"
  publish = "dist"

[[redirects]]
  from = "/conference"
  to = "https://jamstackconf.com/"
  status = 302
