[build]
  command = "npm run build"
  publish = "dist"
  # functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/conference"
  to = "https://jamstackconf.com/sf"
  status = 302

[[redirects]]
  from = "/meetups*"
  to = "/community/meetups:splat"
  status = 302
